server:
  port: 5000

springdoc:
  swagger-ui:
    path: /api/swagger-ui.html
    
management:
  endpoints:
    web:
      exposure:
        include: mappings
    jmx:
      exposure:
        include: health,info

spring:
  datasource:
    url:
    username:
    password:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

