server:
  port: 5050

springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html

management:
  endpoints:
    web:
      exposure:
        include: mappings
    jmx:
      exposure:
        include: health,info

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/activity_api
    username: root
    password: pass
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


logging:
  level:
    root: INFO