server:
  port: 5000

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:aa1lgfbrm2faszi.cpvp4rwekerx.ap-northeast-1.rds.amazonaws.com}:${MYSQL_PORT:3306}/${MYSQL_DB:activity_api}
    username: ${MYSQL_USERNAME:admin}
    password: ${MYSQL_PASSWORD:admin123}

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl