server:
  port: 5050

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/activity_api
    username: root
    password: pass
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl